//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game_of_Life.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color GraphicsPanel1_Backcolor {
            get {
                return ((global::System.Drawing.Color)(this["GraphicsPanel1_Backcolor"]));
            }
            set {
                this["GraphicsPanel1_Backcolor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color GraphicsPanel1_Gridcolor {
            get {
                return ((global::System.Drawing.Color)(this["GraphicsPanel1_Gridcolor"]));
            }
            set {
                this["GraphicsPanel1_Gridcolor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gray")]
        public global::System.Drawing.Color GraphicsPanel1_SelectedBoxColor {
            get {
                return ((global::System.Drawing.Color)(this["GraphicsPanel1_SelectedBoxColor"]));
            }
            set {
                this["GraphicsPanel1_SelectedBoxColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color GraphicsPanel1_SelectedCellNumberColor {
            get {
                return ((global::System.Drawing.Color)(this["GraphicsPanel1_SelectedCellNumberColor"]));
            }
            set {
                this["GraphicsPanel1_SelectedCellNumberColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color GraphicsPanel1_UnselectedCellNumberColor {
            get {
                return ((global::System.Drawing.Color)(this["GraphicsPanel1_UnselectedCellNumberColor"]));
            }
            set {
                this["GraphicsPanel1_UnselectedCellNumberColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int Form1_TimerInterval {
            get {
                return ((int)(this["Form1_TimerInterval"]));
            }
            set {
                this["Form1_TimerInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int Form1_UniverseRows {
            get {
                return ((int)(this["Form1_UniverseRows"]));
            }
            set {
                this["Form1_UniverseRows"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int Form1_UniverseColumns {
            get {
                return ((int)(this["Form1_UniverseColumns"]));
            }
            set {
                this["Form1_UniverseColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color GraphicsPanel1_Gridx10Color {
            get {
                return ((global::System.Drawing.Color)(this["GraphicsPanel1_Gridx10Color"]));
            }
            set {
                this["GraphicsPanel1_Gridx10Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("time")]
        public string Form1_RandomizeStyle {
            get {
                return ((string)(this["Form1_RandomizeStyle"]));
            }
            set {
                this["Form1_RandomizeStyle"] = value;
            }
        }
    }
}
